version: 0.0
os: linux
files:
  - source: /
  destination: ~/fe-sprint-aws-deploy

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
    runas: root
  ApplicationStart:
    - location: scripts/start.sh
    runas: root